data:
  train_urls: ["file://corpus/tiny-corpus/train/docs.jsonl"]
  validation_urls: ["file://corpus/tiny-corpus/validation/docs.jsonl"]
  tokenizer: "gpt2"

model:
  type: gpt2_hyena
  hidden_dim: 32     # Default: 768
  num_layers: 2      # Default: 12
  hyena_filter_order: 16   # Default: 64

trainer:
  mp: bf16
  num_train_steps: 100
  require_accelerator: false

  checkpointer:
    keep:
      - every: 50
    save_interval: 5m

  per_device_parallelism: -1
  train_batch_size: 32

  tensor_parallel_axes: ["mlp"]
  fsdp_axis: "embed"
  batch_axis: "batch"
